server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/allData,/api/v1/employee/**
        - id: COMPENSATION-SERVICE
          uri: lb://COMPENSATION-SERVICE
          predicates:
            - Path=/api/v1/leaves/**,/api/v1/salaries/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/login,/api/v1/validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security.web: DEBUG
