server:
  port: 8084

spring:
  application:
    name: Api_Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true